PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^ClassInfo/', include('apps.ClassInfo.urls', namespace='ClassInfo')),  # 班级信息模块
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 学生信息模块
    url(r'^Teacher/', include('apps.Teacher.urls', namespace='Teacher')),  # 教师信息模块
    url(r'^Subject/', include('apps.Subject.urls', namespace='Subject')),  # 题目信息模块
    url(r'^SubjectType/', include('apps.SubjectType.urls', namespace='SubjectType')),  # 题目类型模块
    url(r'^SelectItem/', include('apps.SelectItem.urls', namespace='SelectItem')),  # 学生选题模块
    url(r'^Leaveword/', include('apps.Leaveword.urls', namespace='Leaveword')),  # 留言模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 新闻公告模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/ClassInfo/urls.py
from apps.ClassInfo.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'ClassInfo'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<classNumber>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<classNumber>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<classNumber>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<classNumber>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import MainTeacherView,IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^main_teacher$', MainTeacherView.as_view(), name='main_teacher'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/ClassInfo/models.py
from django.db import models


class ClassInfo(models.Model):
    classNumber = models.CharField(max_length=20, default='', primary_key=True, verbose_name='班级编号')
    specialName = models.CharField(max_length=20, default='', verbose_name='所在专业')
    className = models.CharField(max_length=20, default='', verbose_name='班级名称')
    startDate = models.CharField(max_length=20, default='', verbose_name='成立日期')
    headTeacher = models.CharField(max_length=12, default='', verbose_name='班主任')

    class Meta:
        db_table = 't_ClassInfo'
        verbose_name = '班级信息信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        classInfo = {
            'classNumber': self.classNumber,
            'specialName': self.specialName,
            'className': self.className,
            'startDate': self.startDate,
            'headTeacher': self.headTeacher,
        }
        return classInfo


PythonProject/apps/ClassInfo/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.ClassInfo.models import ClassInfo
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台班级信息添加
    def primaryKeyExist(self, classNumber):  # 判断主键是否存在
        try:
            ClassInfo.objects.get(classNumber=classNumber)
            return True
        except ClassInfo.DoesNotExist:
            return False

    def get(self,request):

        # 使用模板
        return render(request, 'ClassInfo/classInfo_frontAdd.html')

    def post(self, request):
        classNumber = request.POST.get('classInfo.classNumber') # 判断班级编号是否存在
        if self.primaryKeyExist(classNumber):
            return JsonResponse({'success': False, 'message': '班级编号已经存在'})

        classInfo = ClassInfo() # 新建一个班级信息对象然后获取参数
        classInfo.classNumber = classNumber
        classInfo.specialName = request.POST.get('classInfo.specialName')
        classInfo.className = request.POST.get('classInfo.className')
        classInfo.startDate = request.POST.get('classInfo.startDate')
        classInfo.headTeacher = request.POST.get('classInfo.headTeacher')
        classInfo.save() # 保存班级信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改班级信息
    def get(self, request, classNumber):
        context = {'classNumber': classNumber}
        return render(request, 'ClassInfo/classInfo_frontModify.html', context)


class FrontListView(BaseView):  # 前台班级信息查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        classNumber = self.getStrParam(request, 'classNumber')
        specialName = self.getStrParam(request, 'specialName')
        className = self.getStrParam(request, 'className')
        startDate = self.getStrParam(request, 'startDate')
        # 然后条件组合查询过滤
        classInfos = ClassInfo.objects.all()
        if classNumber != '':
            classInfos = classInfos.filter(classNumber__contains=classNumber)
        if specialName != '':
            classInfos = classInfos.filter(specialName__contains=specialName)
        if className != '':
            classInfos = classInfos.filter(className__contains=className)
        if startDate != '':
            classInfos = classInfos.filter(startDate__contains=startDate)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(classInfos, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        classInfos_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'classInfos_page': classInfos_page,
            'classNumber': classNumber,
            'specialName': specialName,
            'className': className,
            'startDate': startDate,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'ClassInfo/classInfo_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示班级信息详情页
    def get(self, request, classNumber):
        # 查询需要显示的班级信息对象
        classInfo = ClassInfo.objects.get(classNumber=classNumber)
        context = {
            'classInfo': classInfo
        }
        # 渲染模板显示
        return render(request, 'ClassInfo/classInfo_frontshow.html', context)


class ListAllView(View): # 前台查询所有班级信息
    def get(self,request):
        classInfos = ClassInfo.objects.all()
        classInfoList = []
        for classInfo in classInfos:
            classInfoObj = {
                'classNumber': classInfo.classNumber,
                'className': classInfo.className,
            }
            classInfoList.append(classInfoObj)
        return JsonResponse(classInfoList, safe=False)


class UpdateView(BaseView):  # Ajax方式班级信息更新
    def get(self, request, classNumber):
        # GET方式请求查询班级信息对象并返回班级信息json格式
        classInfo = ClassInfo.objects.get(classNumber=classNumber)
        return JsonResponse(classInfo.getJsonObj())

    def post(self, request, classNumber):
        # POST方式提交班级信息修改信息更新到数据库
        classInfo = ClassInfo.objects.get(classNumber=classNumber)
        classInfo.specialName = request.POST.get('classInfo.specialName')
        classInfo.className = request.POST.get('classInfo.className')
        classInfo.startDate = request.POST.get('classInfo.startDate')
        classInfo.headTeacher = request.POST.get('classInfo.headTeacher')
        classInfo.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台班级信息添加
    def primaryKeyExist(self, classNumber):  # 判断主键是否存在
        try:
            ClassInfo.objects.get(classNumber=classNumber)
            return True
        except ClassInfo.DoesNotExist:
            return False

    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'ClassInfo/classInfo_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        classNumber = request.POST.get('classInfo.classNumber') # 判断班级编号是否存在
        if self.primaryKeyExist(classNumber):
            return JsonResponse({'success': False, 'message': '班级编号已经存在'})

        classInfo = ClassInfo() # 新建一个班级信息对象然后获取参数
        classInfo.classNumber = classNumber
        classInfo.specialName = request.POST.get('classInfo.specialName')
        classInfo.className = request.POST.get('classInfo.className')
        classInfo.startDate = request.POST.get('classInfo.startDate')
        classInfo.headTeacher = request.POST.get('classInfo.headTeacher')
        classInfo.save() # 保存班级信息信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新班级信息
    def get(self, request, classNumber):
        context = {'classNumber': classNumber}
        return render(request, 'ClassInfo/classInfo_modify.html', context)


class ListView(BaseView):  # 后台班级信息列表
    def get(self, request):
        # 使用模板
        return render(request, 'ClassInfo/classInfo_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        classNumber = self.getStrParam(request, 'classNumber')
        specialName = self.getStrParam(request, 'specialName')
        className = self.getStrParam(request, 'className')
        startDate = self.getStrParam(request, 'startDate')
        # 然后条件组合查询过滤
        classInfos = ClassInfo.objects.all()
        if classNumber != '':
            classInfos = classInfos.filter(classNumber__contains=classNumber)
        if specialName != '':
            classInfos = classInfos.filter(specialName__contains=specialName)
        if className != '':
            classInfos = classInfos.filter(className__contains=className)
        if startDate != '':
            classInfos = classInfos.filter(startDate__contains=startDate)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(classInfos, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        classInfos_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        classInfoList = []
        for classInfo in classInfos_page:
            classInfo = classInfo.getJsonObj()
            classInfoList.append(classInfo)
        # 构造模板页面需要的参数
        classInfo_res = {
            'rows': classInfoList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(classInfo_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除班级信息信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        classNumbers = self.getStrParam(request, 'classNumbers')
        classNumbers = classNumbers.split(',')
        count = 0
        try:
            for classNumber in classNumbers:
                ClassInfo.objects.get(classNumber=classNumber).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出班级信息信息到excel并下载
    def get(self, request):
        # 收集查询参数
        classNumber = self.getStrParam(request, 'classNumber')
        specialName = self.getStrParam(request, 'specialName')
        className = self.getStrParam(request, 'className')
        startDate = self.getStrParam(request, 'startDate')
        # 然后条件组合查询过滤
        classInfos = ClassInfo.objects.all()
        if classNumber != '':
            classInfos = classInfos.filter(classNumber__contains=classNumber)
        if specialName != '':
            classInfos = classInfos.filter(specialName__contains=specialName)
        if className != '':
            classInfos = classInfos.filter(className__contains=className)
        if startDate != '':
            classInfos = classInfos.filter(startDate__contains=startDate)
        #将查询结果集转换成列表
        classInfoList = []
        for classInfo in classInfos:
            classInfo = classInfo.getJsonObj()

PythonProject/templates/ClassInfo/classInfo_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>班级信息查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div class="col-md-3 wow fadeInLeft">
		<div class="page-header">
    		<h1>班级信息查询</h1>
		</div>
		<form name="classInfoQueryForm" id="classInfoQueryForm" action="{% url 'ClassInfo:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
			<div class="form-group">
				<label for="classNumber">班级编号:</label>
				<input type="text" id="classNumber" name="classNumber" value="{{ classNumber }}" class="form-control" placeholder="请输入班级编号">
			</div>
			<div class="form-group">
				<label for="specialName">所在专业:</label>
				<input type="text" id="specialName" name="specialName" value="{{ specialName }}" class="form-control" placeholder="请输入所在专业">
			</div>
			<div class="form-group">
				<label for="className">班级名称:</label>
				<input type="text" id="className" name="className" value="{{ className }}" class="form-control" placeholder="请输入班级名称">
			</div>
			<div class="form-group">
				<label for="startDate">成立日期:</label>
				<input type="text" id="startDate" name="startDate" class="form-control"  placeholder="请选择成立日期" value="{{ startDate }}" onclick="SelectDate(this,'yyyy-MM-dd')" />
			</div>
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-9 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#classInfoListPanel" aria-controls="classInfoListPanel" role="tab" data-toggle="tab">班级信息列表</a></li>
			    	<li role="presentation" ><a href="{% url 'ClassInfo:frontAdd' %}" style="display:none;">添加班级信息</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="classInfoListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>班级编号</td><td>所在专业</td><td>班级名称</td><td>成立日期</td><td>班主任</td><td>操作</td></tr>
                                        {% for classInfo in classInfos_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ classInfo.classNumber }}</td>
 											<td>{{ classInfo.specialName }}</td>
 											<td>{{ classInfo.className }}</td>
 											<td>{{ classInfo.startDate }}</td>
 											<td>{{ classInfo.headTeacher }}</td>
 											<td>
 												<a href="{% url 'ClassInfo:frontShow' classInfo.classNumber  %}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="classInfoEdit('{{ classInfo.classNumber }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="classInfoDelete('{{ classInfo.classNumber }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="classInfoEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;班级信息信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="classInfoEditForm" id="classInfoEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="classInfo_classNumber_edit" class="col-md-3 text-right">班级编号:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="classInfo_classNumber_edit" name="classInfo.classNumber" class="form-control" placeholder="请输入班级编号" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="classInfo_specialName_edit" class="col-md-3 text-right">所在专业:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="classInfo_specialName_edit" name="classInfo.specialName" class="form-control" placeholder="请输入所在专业">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="classInfo_className_edit" class="col-md-3 text-right">班级名称:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="classInfo_className_edit" name="classInfo.className" class="form-control" placeholder="请输入班级名称">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="classInfo_startDate_edit" class="col-md-3 text-right">成立日期:</label>
		  	 <div class="col-md-9">
                <div class="input-group date classInfo_startDate_edit col-md-12" data-link-field="classInfo_startDate_edit"  data-link-format="yyyy-mm-dd">
                    <input class="form-control" id="classInfo_startDate_edit" name="classInfo.startDate" size="16" type="text" value="" placeholder="请选择成立日期" readonly>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                </div>
		  	 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="classInfo_headTeacher_edit" class="col-md-3 text-right">班主任:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="classInfo_headTeacher_edit" name="classInfo.headTeacher" class="form-control" placeholder="请输入班主任">
			 </div>
		  </div>
		</form> 
	    <style>#classInfoEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxClassInfoModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.classInfoQueryForm.currentPage.value = currentPage;
    document.classInfoQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.classInfoQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.classInfoQueryForm.currentPage.value = pageValue;
    documentclassInfoQueryForm.submit();
}

/*弹出修改班级信息界面并初始化数据*/
function classInfoEdit(classNumber) {
	$.ajax({
		url :  '/ClassInfo/update/' + classNumber,
		type : "get",
		dataType: "json",
		success : function (classInfo, response, status) {
			if (classInfo) {
				$("#classInfo_classNumber_edit").val(classInfo.classNumber);
				$("#classInfo_specialName_edit").val(classInfo.specialName);
				$("#classInfo_className_edit").val(classInfo.className);
				$("#classInfo_startDate_edit").val(classInfo.startDate);
				$("#classInfo_headTeacher_edit").val(classInfo.headTeacher);
				$('#classInfoEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除班级信息信息*/
function classInfoDelete(classNumber) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/ClassInfo/deletes",
			data : {
				classNumbers : classNumber,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#classInfoQueryForm").submit();
					//location.href= basePath + "ClassInfo/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交班级信息信息表单给服务器端修改*/
function ajaxClassInfoModify() {
	$.ajax({
		url :   '/ClassInfo/update/' + $("#classInfo_classNumber_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#classInfoEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                $("#classInfoQueryForm").submit();
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

    /*成立日期组件*/
    $('.classInfo_startDate_edit').datetimepicker({
    	language:  'zh-CN',  //语言
    	format: 'yyyy-mm-dd',
    	minView: 2,
    	weekStart: 1,
    	todayBtn:  1,
    	autoclose: 1,
    	minuteStep: 1,
    	todayHighlight: 1,
    	startView: 2,
    	forceParse: 0
    });
})
</script>
</body>
</html>
