PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^ClassInfo/', include('apps.ClassInfo.urls', namespace='ClassInfo')),  # 班级信息模块
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 学生信息模块
    url(r'^Teacher/', include('apps.Teacher.urls', namespace='Teacher')),  # 教师信息模块
    url(r'^Subject/', include('apps.Subject.urls', namespace='Subject')),  # 题目信息模块
    url(r'^SubjectType/', include('apps.SubjectType.urls', namespace='SubjectType')),  # 题目类型模块
    url(r'^SelectItem/', include('apps.SelectItem.urls', namespace='SelectItem')),  # 学生选题模块
    url(r'^Leaveword/', include('apps.Leaveword.urls', namespace='Leaveword')),  # 留言模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 新闻公告模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import MainTeacherView,IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^main_teacher$', MainTeacherView.as_view(), name='main_teacher'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/SubjectType/urls.py
from apps.SubjectType.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'SubjectType'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<subjectTypeId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<subjectTypeId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<subjectTypeId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<subjectTypeId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/SubjectType/models.py
from django.db import models


class SubjectType(models.Model):
    subjectTypeId = models.AutoField(primary_key=True, verbose_name='类型编号')
    subjectTypeName = models.CharField(max_length=20, default='', verbose_name='类型名称')
    subjectTypeDesc = models.CharField(max_length=500, default='', verbose_name='类型说明')

    class Meta:
        db_table = 't_SubjectType'
        verbose_name = '题目类型信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        subjectType = {
            'subjectTypeId': self.subjectTypeId,
            'subjectTypeName': self.subjectTypeName,
            'subjectTypeDesc': self.subjectTypeDesc,
        }
        return subjectType


PythonProject/apps/SubjectType/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.SubjectType.models import SubjectType
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台题目类型添加
    def get(self,request):

        # 使用模板
        return render(request, 'SubjectType/subjectType_frontAdd.html')

    def post(self, request):
        subjectType = SubjectType() # 新建一个题目类型对象然后获取参数
        subjectType.subjectTypeName = request.POST.get('subjectType.subjectTypeName')
        subjectType.subjectTypeDesc = request.POST.get('subjectType.subjectTypeDesc')
        subjectType.save() # 保存题目类型信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改题目类型
    def get(self, request, subjectTypeId):
        context = {'subjectTypeId': subjectTypeId}
        return render(request, 'SubjectType/subjectType_frontModify.html', context)


class FrontListView(BaseView):  # 前台题目类型查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        # 然后条件组合查询过滤
        subjectTypes = SubjectType.objects.all()
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(subjectTypes, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        subjectTypes_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'subjectTypes_page': subjectTypes_page,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'SubjectType/subjectType_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示题目类型详情页
    def get(self, request, subjectTypeId):
        # 查询需要显示的题目类型对象
        subjectType = SubjectType.objects.get(subjectTypeId=subjectTypeId)
        context = {
            'subjectType': subjectType
        }
        # 渲染模板显示
        return render(request, 'SubjectType/subjectType_frontshow.html', context)


class ListAllView(View): # 前台查询所有题目类型
    def get(self,request):
        subjectTypes = SubjectType.objects.all()
        subjectTypeList = []
        for subjectType in subjectTypes:
            subjectTypeObj = {
                'subjectTypeId': subjectType.subjectTypeId,
                'subjectTypeName': subjectType.subjectTypeName,
            }
            subjectTypeList.append(subjectTypeObj)
        return JsonResponse(subjectTypeList, safe=False)


class UpdateView(BaseView):  # Ajax方式题目类型更新
    def get(self, request, subjectTypeId):
        # GET方式请求查询题目类型对象并返回题目类型json格式
        subjectType = SubjectType.objects.get(subjectTypeId=subjectTypeId)
        return JsonResponse(subjectType.getJsonObj())

    def post(self, request, subjectTypeId):
        # POST方式提交题目类型修改信息更新到数据库
        subjectType = SubjectType.objects.get(subjectTypeId=subjectTypeId)
        subjectType.subjectTypeName = request.POST.get('subjectType.subjectTypeName')
        subjectType.subjectTypeDesc = request.POST.get('subjectType.subjectTypeDesc')
        subjectType.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台题目类型添加
    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'SubjectType/subjectType_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        subjectType = SubjectType() # 新建一个题目类型对象然后获取参数
        subjectType.subjectTypeName = request.POST.get('subjectType.subjectTypeName')
        subjectType.subjectTypeDesc = request.POST.get('subjectType.subjectTypeDesc')
        subjectType.save() # 保存题目类型信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新题目类型
    def get(self, request, subjectTypeId):
        context = {'subjectTypeId': subjectTypeId}
        return render(request, 'SubjectType/subjectType_modify.html', context)


class ListView(BaseView):  # 后台题目类型列表
    def get(self, request):
        # 使用模板
        return render(request, 'SubjectType/subjectType_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        # 然后条件组合查询过滤
        subjectTypes = SubjectType.objects.all()
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(subjectTypes, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        subjectTypes_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        subjectTypeList = []
        for subjectType in subjectTypes_page:
            subjectType = subjectType.getJsonObj()
            subjectTypeList.append(subjectType)
        # 构造模板页面需要的参数
        subjectType_res = {
            'rows': subjectTypeList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(subjectType_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除题目类型信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        subjectTypeIds = self.getStrParam(request, 'subjectTypeIds')
        subjectTypeIds = subjectTypeIds.split(',')
        count = 0
        try:
            for subjectTypeId in subjectTypeIds:
                SubjectType.objects.get(subjectTypeId=subjectTypeId).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出题目类型信息到excel并下载
    def get(self, request):
        # 收集查询参数
        # 然后条件组合查询过滤
        subjectTypes = SubjectType.objects.all()
        #将查询结果集转换成列表
        subjectTypeList = []
        for subjectType in subjectTypes:
            subjectType = subjectType.getJsonObj()
            subjectTypeList.append(subjectType)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(subjectTypeList)
        # 设置要导入到excel的列
        columns_map = {
            'subjectTypeId': '类型编号',
            'subjectTypeName': '类型名称',
            'subjectTypeDesc': '类型说明',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径
        filename = 'subjectTypes.xlsx'
        # 这个路径可以在settings中设置也可以直接手动输入
        root_path = settings.MEDIA_ROOT + '/output/'
        file_path = os.path.join(root_path, filename)
        pf.to_excel(file_path, encoding='utf-8', index=False)
        # 将生成的excel文件输出到网页下载
        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="subjectTypes.xlsx"'
        return response


PythonProject/templates/SubjectType/subjectType_frontAdd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>题目类型添加</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
{% include 'header.html' %}
<div class="container">
	<div class="row">
		<div class="col-md-12 wow fadeInUp" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li role="presentation" ><a href="{% url 'SubjectType:frontList' %}">题目类型列表</a></li>
			    	<li role="presentation" class="active"><a href="#subjectTypeAdd" aria-controls="subjectTypeAdd" role="tab" data-toggle="tab">添加题目类型</a></li>
				</ul>
				<!-- Tab panes -->
				<div class="tab-content">
				    <div role="tabpanel" class="tab-pane" id="subjectTypeList">
				    </div>
				    <div role="tabpanel" class="tab-pane active" id="subjectTypeAdd"> 
				      	<form class="form-horizontal" name="subjectTypeAddForm" id="subjectTypeAddForm" enctype="multipart/form-data" method="post"  class="mar_t15">
				    {% csrf_token %}
						  <div class="form-group">
						  	 <label for="subjectType_subjectTypeName" class="col-md-2 text-right">类型名称:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="subjectType_subjectTypeName" name="subjectType.subjectTypeName" class="form-control" placeholder="请输入类型名称">
							 </div>
						  </div>
						  <div class="form-group">
						  	 <label for="subjectType_subjectTypeDesc" class="col-md-2 text-right">类型说明:</label>
						  	 <div class="col-md-8">
							    <textarea id="subjectType_subjectTypeDesc" name="subjectType.subjectTypeDesc" rows="8" class="form-control" placeholder="请输入类型说明"></textarea>
							 </div>
						  </div>
				          <div class="form-group">
				             <span class="col-md-2"></span>
				             <span onclick="ajaxSubjectTypeAdd();" class="btn btn-primary bottom5 top5">添加</span>
				          </div>
						</form> 
				        <style>#subjectTypeAddForm .form-group {margin:10px;}  </style>
					</div>
				</div>
			</div>
		</div>
	</div> 
</div>

{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrapvalidator/js/bootstrapValidator.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
<script>
	//提交添加题目类型信息
	function ajaxSubjectTypeAdd() { 
		//提交之前先验证表单
		$("#subjectTypeAddForm").data('bootstrapValidator').validate();
		if(!$("#subjectTypeAddForm").data('bootstrapValidator').isValid()){
			return;
		}
		jQuery.ajax({
			type : "post",
			url : "{% url 'SubjectType:frontAdd' %}",
			dataType : "json" , 
			data: new FormData($("#subjectTypeAddForm")[0]),
			success : function(obj) {
				if(obj.success){ 
					alert("保存成功！");
					location.reload();
				} else {
					alert(obj.message);
				}
			},
			processData: false, 
			contentType: false, 
		});
	} 
$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();
	//验证题目类型添加表单字段
	$('#subjectTypeAddForm').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			"subjectType.subjectTypeName": {
				validators: {
					notEmpty: {
						message: "类型名称不能为空",
					}
				}
			},
			"subjectType.subjectTypeDesc": {
				validators: {
					notEmpty: {
						message: "类型说明不能为空",
					}
				}
			},
		}
	}); 
})
</script>
</body>
</html>

PythonProject/templates/SubjectType/subjectType_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>题目类型查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div style="display:none;">
		<div class="page-header">
    		<h1>题目类型查询</h1>
		</div>
		<form name="subjectTypeQueryForm" id="subjectTypeQueryForm" action="{% url 'SubjectType:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-12 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#subjectTypeListPanel" aria-controls="subjectTypeListPanel" role="tab" data-toggle="tab">题目类型列表</a></li>
			    	<li role="presentation" ><a href="{% url 'SubjectType:frontAdd' %}" style="display:none;">添加题目类型</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="subjectTypeListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>类型编号</td><td>类型名称</td><td>类型说明</td><td>操作</td></tr>
                                        {% for subjectType in subjectTypes_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ subjectType.subjectTypeId }}</td>
 											<td>{{ subjectType.subjectTypeName }}</td>
 											<td>{{ subjectType.subjectTypeDesc }}</td>
 											<td>
 												<a href="/Subject/frontList?subjectTypeObj.subjectTypeId={{ subjectType.subjectTypeId }}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="subjectTypeEdit('{{ subjectType.subjectTypeId }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="subjectTypeDelete('{{ subjectType.subjectTypeId }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="subjectTypeEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;题目类型信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="subjectTypeEditForm" id="subjectTypeEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="subjectType_subjectTypeId_edit" class="col-md-3 text-right">类型编号:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="subjectType_subjectTypeId_edit" name="subjectType.subjectTypeId" class="form-control" placeholder="请输入类型编号" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="subjectType_subjectTypeName_edit" class="col-md-3 text-right">类型名称:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="subjectType_subjectTypeName_edit" name="subjectType.subjectTypeName" class="form-control" placeholder="请输入类型名称">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="subjectType_subjectTypeDesc_edit" class="col-md-3 text-right">类型说明:</label>
		  	 <div class="col-md-9">
			    <textarea id="subjectType_subjectTypeDesc_edit" name="subjectType.subjectTypeDesc" rows="8" class="form-control" placeholder="请输入类型说明"></textarea>
			 </div>
		  </div>
		</form> 
	    <style>#subjectTypeEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxSubjectTypeModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.subjectTypeQueryForm.currentPage.value = currentPage;
    document.subjectTypeQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.subjectTypeQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.subjectTypeQueryForm.currentPage.value = pageValue;
    documentsubjectTypeQueryForm.submit();
}

/*弹出修改题目类型界面并初始化数据*/
function subjectTypeEdit(subjectTypeId) {
	$.ajax({
		url :  '/SubjectType/update/' + subjectTypeId,
		type : "get",
		dataType: "json",
		success : function (subjectType, response, status) {
			if (subjectType) {
				$("#subjectType_subjectTypeId_edit").val(subjectType.subjectTypeId);
				$("#subjectType_subjectTypeName_edit").val(subjectType.subjectTypeName);
				$("#subjectType_subjectTypeDesc_edit").val(subjectType.subjectTypeDesc);
				$('#subjectTypeEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除题目类型信息*/
function subjectTypeDelete(subjectTypeId) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/SubjectType/deletes",
			data : {
				subjectTypeIds : subjectTypeId,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#subjectTypeQueryForm").submit();
					//location.href= basePath + "SubjectType/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交题目类型信息表单给服务器端修改*/
function ajaxSubjectTypeModify() {
	$.ajax({
		url :   '/SubjectType/update/' + $("#subjectType_subjectTypeId_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#subjectTypeEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                location.href= basePath + "SubjectType/frontlist";
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

})
</script>
</body>
</html>
